baseURL = "https://charly3pins.github.io/onepiecefigures/"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Portrait of Pirates - The final guide of figures"
    weight = 1
  [languages.es]
    title = "Portrait of Pirates - La guia definitiva de las figuras"
    weight = 2

[Params]
  homeTitle = " "
  favicon = "images/favicon.ico"
  readingTime = true
  socialShare = true

[Author]
  name = "Charly3Pins & ucles83"